name: 3_Aug_2023
colab: True
device: cpu # cuda

dataset:
  train_path: 'asl_alphabet_train/asl_alphabet_train'
  test_path: 'asl_alphabet_test/asl_alphabet_test'
  transforms: True
  imsize: 128
  shuffle: True
  batch_size: 16

network:
  arch: resnet
  block_type: bottleneck # resblock
  num_blocks: 1
  in_nc: 3
  nc: 3
  out_nc: 29

optimizer:
  name: adam
  lr: 0.001
  beta1: 0.9
  beta2: 0.999

train:
  benchmark: True
  deterministic: False
  epochs: 10
  use_amp: True
  validate: False

